language: node_js
node_js:
  - node
cache: yarn
env:
  matrix:
    - REACT_VERSION=15.2.0
    - REACT_VERSION=15.6.1
    - REACT_VERSION=16.0.0
    - REACT_VERSION=16.1.0
    - VUE_VERSION=2.2.0
    - VUE_VERSION=2.3.4
    - VUE_VERSION=2.4.4
    - VUE_VERSION=2.5
install:
  - yarn install
  - yarn add -D react@$REACT_VERSION react-dom@$REACT_VERSION vue@$VUE_VERSION vue-template-compiler@$VUE_VERSION
script:
  - yarn lint
  - yarn run test:coverage -- --coverageReporters=lcov
  - cat ./coverage/lcov.info | yarn run coveralls

branches:
  only:
    - master
